name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Change to your main branch if it's different
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use the Node.js version that matches your project

      - name: Install dependencies
        run: |
          npm install

      - name: Run Playwright Tests
        run: |
          npx playwright test  # Modify if your test command is different

      - name: Upload Test Results
        if: always()
        run: |
          mkdir -p test-results
          npx playwright show-report  # This generates a report; modify as needed
          mv test-results/* ./test-results/

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./test-results
